name: Microsoft Word
reg: word
icon: icon.svg
opens:
    application/msword
    application/vnd.openxmlformats-officedocument.wordprocessingml.document
    application/vnd.openxmlformats-officedocument.wordprocessingml.template
    application/vnd.ms-word.document.macroEnabled.12;application/vnd.ms-word.template.macroEnabled.12
keywords:
    - word
    - office
